### ISSUE TITLE
Solicitud de modelo

### ISSUE THREAD

**Issue by theotocopulitos** [CarlosGS/facemask-print-vertical#4]
¿Se puede generar un modelo apilable del adjunto? (es el "oficial" de Castilla y León)
[PANTALLA_SACYL_3.1.zip](https://github.com/CarlosGS/facemask-print-vertical/files/4431765/PANTALLA_SACYL_3.1.zip)

**Comment by CarlosGS** [comment]
Añadido, dime si lo consigues!! :)
https://github.com/CarlosGS/facemask-print-vertical/tree/master/stl/PANTALLA_SACYL

**Comment by theotocopulitos** [comment]
Carlos,

Mil gracias. Esta noche he probado la de 5, y perfecto... se separan
bien... todo genial. Me ha salido mal, curiosamente, la 4ª, pero las de
abajo y las de arriba perfectas... en cuanto ajuste un poco los parámetros,
a tope.

Muchas gracias, has mejorado infinitamente la calidad de mi sueño...

Arturo

**Comment by CarlosGS** [comment]
Bieeen :-)
Pasa foto del resultado para ver qué pudo pasar. Utilizas Cura?

**Comment by theotocopulitos** [comment]
De las otras dos quedaron muy bien y dos utilizables con un poco de lija previa. Esta no recuerdo si es la 3 o 4. 

Sí uso Cura

**Comment by CarlosGS** [comment]
Vaya, no se ha mandado! Prueba a adjuntarla desde la web de github mejor. Si puedes saca foto de la pila completa. Gracias!!

**Comment by theotocopulitos** [comment]
A ver si así las ves... no tengo fotos del pack.

Tengo de tres, y la que salió mal... La de abajo salió perfecta. Parece como que al empezar cada nueva pieza hay retracción y se mete un poco el arco...a partir de la 3ª o 4ª capas superiores se coloca bien... salvo en la que quedó mal que ese efecto pilló muchas más capas y fue mucho más acusado.

![unnamed (1)](https://user-images.githubusercontent.com/1540135/78505605-db74d480-7774-11ea-8567-c5508576835a.jpg)
![unnamed](https://user-images.githubusercontent.com/1540135/78505606-dca60180-7774-11ea-9c24-bf719040724e.jpg)
![IMG_8255](https://user-images.githubusercontent.com/1540135/78505608-de6fc500-7774-11ea-9216-183070bb38ed.JPG)

**Comment by theotocopulitos** [comment]
No me di cuenta de usar tu perfil... sí verifiqué capas vacías, pero me olvidé del perfil que pones

**Comment by CarlosGS** [comment]
Gracias! Ya veo!
El perfil lo saqué de aquí: https://twitter.com/MKmeOrg/status/1243522985262186496

Yo no me molestaría en cambiarlo, creo que el problema está relacionado con el bisel que tienen algunas máscaras en la base:
![Screenshot_20200405_194647](https://user-images.githubusercontent.com/1636266/78505834-5c809b80-7776-11ea-9287-1fc7c83ed0bf.png)

**Comment by theotocopulitos** [comment]
Vaya...

también veo que ses perfil tiene espesor de capa 0.2... el mío 0.3... no creo que influya, pero...
